functionsDirectory = "/Users/osamaeldrieny/Sandbox/Nintex Connector Priotrizer/netlify/functions"
functionsDirectoryOrigin = "default"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/Users/osamaeldrieny/Sandbox/Nintex Connector Priotrizer"
publishOrigin = "config"
functions = "/Users/osamaeldrieny/Sandbox/Nintex Connector Priotrizer/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]